---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginxdpm
  namespace: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers: 
      - image: dockerminhthien2207/nginx-simple
        name: nginx
        resources: {}
---
